title: nathancalandra.cloud
description: Nathan Calandra's Website
author: Nathan Calandra
email: njcalandra@gmail.com
baseurl: ""
url: "https://nathancalandra.cloud"
github_username: ncalandra
linkedin_username: nathan-calandra

theme: minima
plugins:
  - jekyll-feed
